In [25]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [26]:
df = pd.read_csv('C:/Users/Janane Sundar/Documents/bml/multivaraent.csv')
print (df)

   Experience  Test_score  Interview_score  Salary
0         NaN         8.0                9   50000
1         NaN         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000


In [27]:
import math
median_Test_score = math.floor(df['Test_score'].mean())
median_Test_score

7

In [28]:
df['Test_score'] = df['Test_score'].fillna(median_Test_score)
df

Experience  Test_score  Interview_score  Salary
0         NaN         8.0                9   50000
1         NaN         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         7.0                7   72000
7        11.0         7.0                8   80000

In [31]:
import math
median_Experience = math.floor(df.Experience.median())
median_Experience

6

In [32]:
df.Experience = df.Experience.fillna(median_Experience)
df

Experience  Test_score  Interview_score  Salary
0         6.0         8.0                9   50000
1         6.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         7.0                7   72000
7        11.0         7.0                8   80000

In [34]:
reg = linear_model.LinearRegression()
reg.fit(df[['Experience','Test_score','Interview_score']],df.Salary)

LinearRegression()

In [36]:
reg.coef_

array([2874.43853793, 1225.36778341, 2941.77277785])

In [37]:
reg.intercept_

12371.698190958916

In [38]:
reg.predict([[2,9,6]])

C:\Users\Janane Sundar\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([46799.52198459])

In [39]:
2813.00813008*2+1333.33333333*9+2926.82926829*6+11869.91869918698

47056.910569056985

In [40]:
reg.predict([[12,10,10]])

C:\Users\Janane Sundar\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([88536.36625871])